live_config_reload = true

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
dynamic_title = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#575656"
blue = "#82AAFF"
cyan = "#7fdbca"
green = "#22da6e"
magenta = "#C792EA"
red = "#EF5350"
white = "#ffffff"
yellow = "#ffeb95"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#011627"
blue = "#82AAFF"
cyan = "#21c7a8"
green = "#22da6e"
magenta = "#C792EA"
red = "#EF5350"
white = "#ffffff"
yellow = "#c5e478"

[colors.primary]
background = "#011627"
foreground = "#d6deeb"

[colors.search.matches]
background = "#22da6e"
foreground = "#000000"

[colors.selection]
background = "#0d486e"
text = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#22da6e"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["new-session", "-A", "-s", "tmdev"]
program = "/usr/bin/tmux"
